version: '3.8'

services:

# n8n

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH=true
      - N8N_BASIC_AUTH_USERNAME=myusername
      - N8N_BASIC_AUTH_PASSWORD=mypassword

# MySQL

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
